x<-read.table("household_power_consumption.txt",sep=";", header=T, colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),na.strings='?')
x$DateTime <- strptime(paste(x$Date, x$Time),"%d/%m/%Y %H:%M:%S")
s <- subset(x,as.Date(DateTime) >= as.Date("2007-02-01")&as.Date(DateTime) <= as.Date("2007-02-02"))
par(oma=c(0,0,0,0),mfrow=c(2,2),mar=c(4,4,2,2))
plot(s$DateTime, s$Global_active_power, xlab="", ylab="Global Active Power(kilowatt)", type="l",lty=1)
plot(s$DateTime, s$Voltage, xlab="datetime", ylab="Voltage", type="l")
axis(side=2, at=seq(234, 246, 4))
plot(s$DateTime, s$Sub_metering_1, yaxt="n", xlab="", ylab="Energy Sub metering",type="l")
lines(s$DateTime, s$Sub_metering_2, col="red")
lines(s$DateTime, s$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n", lty=1, col=c("black","red","blue"),cex=0.6)
plot(s$DateTime, s$Global_reactive_power, xlab="datetime", ylab="Global_reactive_energy", type="l")
axis(side=2, at=seq(0.0, 0.5, 0.1))
dev.copy(png,filename="Plot4.png",height=480, width=480,bg="transparent")
dev.off()