par(oma=c(0,0,0,0),mfrow=c(2,2),mar=c(4,4,2,2))
plot(s$DateTime, s$Global_active_power, xlab="", ylab="Global Active Power(kilowatt)", type="l",lty=1)
plot(s$DateTime, s$Voltage, xlab="datetime", ylab="Voltage", type="l")
axis(side=2, at=seq(234, 246, 4))
plot(s$DateTime, s$Sub_metering_1, yaxt="n", xlab="", ylab="Energy Sub metering",type="l")
lines(s$DateTime, s$Sub_metering_2, col="red")
lines(s$DateTime, s$Sub_metering_3, col="blue")
legend("topright",legend=c("sub_metering_1","sub_metering_2","sub_metering_3"),lty=1, col=c("black","red","blue"),cex=0.8)
plot(s$DateTime, s$Global_reactive_power, xlab="datetime", ylab="Global_reactive_energy", type="l")
axis(side=2, at=seq(0.0, 0.5, 0.1))
dev.copy(png,filename="Plot4.png",height=480, width=480,bg="transparent")
dev.off()