x<-read.table("household_power_consumption.txt",sep=";", header=T, colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),na.strings='?')
x$DateTime <- strptime(paste(x$Date, x$Time),"%d/%m/%Y %H:%M:%S")
s <- subset(x,as.Date(DateTime) >= as.Date("2007-02-01")&as.Date(DateTime) <= as.Date("2007-02-02"))
plot(s$DateTime, s$Global_active_power, xlab="", ylab="Global Active Power(kilowatt)", type="l",lty=1)
dev.copy(png,filename="Plot2.png",height=480, width=480,bg="transparent")
dev.off()