x<-read.table("household_power_consumption.txt",sep=";", header=T, colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),na.strings='?')
x$DateTime <- strptime(paste(x$Date, x$Time),"%d/%m/%Y %H:%M:%S")
s <- subset(x,as.Date(DateTime) >= as.Date("2007-02-01")&as.Date(DateTime) <= as.Date("2007-02-02"))
plot(s$DateTime, s$Sub_metering_1, yaxt="n", xlab="", ylab="Energy Sub metering",type="l")
lines(s$DateTime, s$Sub_metering_2, col="red")
lines(s$DateTime, s$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1, col=c("black","red","blue"),cex=0.8)
dev.copy(png,filename="Plot3.png",height=480, width=480,bg="transparent")
dev.off()